---
# Set to 'true' to configure the Dock via dockutil.
configure_dofiles: true
configure_dock: true
configure_sudoers: false 

sudoers_custom_config: |
  Allow users in admin group to use sudo with no password.
  %admin ALL=(ALL) NOPASSWD: ALL

dockitems_to_remove:
  - Launchpad
  - Safari
  - Contacts
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - 'App Store'
  - 'IntelliJ IDEA Ultimate'
  - 'Activity Monitor'
  - System Preferences
  - Pages
  - Reminders
  - Numbers
  - Keynote
  - Calendar
  - Notes
  - TV
  - Music
  - Podcasts
  - News

dockitems_to_persist:
  - name: Messages
    path: "/System/Applications/Messages.app/"
    pos: 1
  - name: Safari
    path: "/Applications/Safari.app/"
    pos: 2
  - name: Sublime Text
    path: "/Applications/Sublime\ Text.app/"
    pos: 3
  - name: iTerm
    path: "/Applications/iTerm.app"
    pos: 4 
  - name: "Google Chrome"
    path: "/Applications/Google\ Chrome.app"
    pos: 5
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 6
  - name: ActiveMonitor
    path: "/System/Applications/Utilities/Activity\ Monitor.app"
    pos: 8

dotfiles_repo: https://github.com/racinepilote/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .gitconfig
  - .gitmessage
  - .aliases
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - github/gh/gh
  - go
  - gpg
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - php
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - zsh-history-substring-search
  - yarn
  - php
  - redis
  - terraform

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - dropbox
  - firefox
  - google-chrome
  - licecap
  - sequel-pro
  - sublime-text
  - transmit
  - microsoft-teams
  - stats
  - parallels
  - iterm2
  - notion
  - zoom
  - nordvpn
  - virtualbox
  - spotify
  - jetbrains-toolbox
  - postman
  - visual-studio-code

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1333542190, name: "1Password" }
  - { id: 1303222628, name: "Paprika" }
  - { id: 1303222628, name: "Paprika" }
  - { id: 1295203466, name: "Microsoft Remote Desktop" }
  - { id: 462054704, name: "Microsoft Word" }
  - { id: 462058435, name: "Microsoft Excel" }
  - { id: 462062816, name: "Microsoft PowerPoint" }
  - { id: 1142051783, name: "LG Screen Manager" }
  - { id: 1478447657, name: "Geekbench 5" }
  - { id: 1116599239, name: "NordVPN IKE" }
  - { id: 803453959, name: "Slack for Desktop" }
  - { id: 406056744, name: "Evernote" }

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: true
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
